version: '3'

services:
  test:
    build: .
    command: yarn test
    depends_on:
      - web

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"